### ISSUE TITLE
Bug: footprint libraries aren't in repo

### ISSUE THREAD

**Issue by DeflateAwning** [ebastler/UnMechanical#5]
The footprint libraries aren't in this repo. They appear to be Global libraries, which reference a path on your computer.

It would be awesome if you could copy them into a project-specific library so they can be used within the repo. It's too bad this isn't the default.

**Comment by ebastler** [comment]
Hi, the project uses my PCM lib [marbastlib](https://github.com/ebastler/marbastlib) - it references relative paths to the place where the KiCad PCM automatically installs libraries. If you want to use/access those footprints, you will have to install said library on your system.

Maintaining separate per-project libraries is way too much effort, and keeps me from improving and bugfixing footprints over time. Submodules make this a bit better, but are still a huge pain with relative paths to 3D models if everyone installs them to different paths. Using the KiCad package manager system for global libraries is the more effective approach.

Since KiCad caches all symbols/footprints in the project anyway, People can still use and edit the projects even without having the library installed anyway.
